repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: '\.rs$'
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: cargo-fmt-clippy
        name: Cargo fmt and clippy
        entry: bash -c "./pre-commit-rust.sh"
        language: system
        pass_filenames: false
